export default {
  RENDERER_ROUTER_PUSH: 'RENDERER_ROUTER_PUSH',
  RENDERER_ROUTER_CLOSE: 'RENDERER_ROUTER_CLOSE',
  MAIN_ROUTER_CONNECT: 'MAIN_ROUTER_CONNECT',
  MESSAGE_CONNECT_REQUEST: 'MESSAGE_CONNECT_REQUEST',
  MESSAGE_CONNECT_RESPONSE: 'MESSAGE_CONNECT_RESPONSE'
}
